spring:
  application:
    name: LibraryManagement
  datasource:
    url: jdbc:mysql://localhost:3306/library_management
    username: root
    password: root
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
    defer-datasource-initialization: true
  #    show-sql: true
  sql:
    init:
      data-locations: classpath:sql-data/*.sql
      mode: always
  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  error:
    whitelabel:
      enabled: false
